api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dep"
    sha256 = "12764a882ab16a6b60d5cfbf69bf8553ac083c4c2589f17e2f052864e592922f"
    source = "https://github.com/paketo-buildpacks/dep/archive/v0.0.144.tar.gz"
    source_sha256 = "4177fd64472dc79db7302e0cc91e9cf8ed41255b839156dc730abeea6aaeaec6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/dep/releases/download/v0.0.144/dep-0.0.144.tgz"
    version = "0.0.144"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-dist"
    sha256 = "9065cc7a538cc1545ff83c99772604727676cef1d4dd070d2bbdd5782d0d57ca"
    source = "https://github.com/paketo-buildpacks/go-dist/archive/v0.0.171.tar.gz"
    source_sha256 = "0ffdeb7b1c9d11eacc88ca750b035dc445e29453b1e91b951d81797ca432df60"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/go-dist/releases/download/v0.0.171/go-dist-0.0.171.tgz"
    version = "0.0.171"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-mod"
    sha256 = "33f69cd157b699270020d2149d04eda8e0c7041fc11319ee32c0a85784723142"
    source = "https://github.com/paketo-buildpacks/go-mod/archive/v0.0.132.tar.gz"
    source_sha256 = "947760c547c0895e3c285e8e2410da908d7165e7c9736af5b8b5bae0e8811833"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-mod/releases/download/v0.0.132/go-mod-0.0.132.tgz"
    version = "0.0.132"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.171"

  [[order.group]]
    id = "paketo-buildpacks/go-mod"
    version = "0.0.132"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.171"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.144"
