api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dep"
    sha256 = "5d0939a0d36e293c2599f0db3aa4b01de1f7db434ad29a240f7cc9857e794aa2"
    source = "https://github.com/paketo-buildpacks/dep/archive/v0.0.137.tar.gz"
    source_sha256 = "14dec1303b54d0473cdd0bcb0b3f72cc05324be3f2c7c223d24e30d2e0051100"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/dep/releases/download/v0.0.137/dep-0.0.137.tgz"
    version = "0.0.137"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-compiler"
    sha256 = "62b4a3ae4520b000446ae99040c3debf54d4fa5dcd6089b2b6d1f98d19360dac"
    source = "https://github.com/paketo-buildpacks/go-compiler/archive/v0.0.156.tar.gz"
    source_sha256 = "16a7884fbe50137e75c8cccb5faae0f65fae28f6809365ccc8be82e1da294e03"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-compiler/releases/download/v0.0.156/go-compiler-0.0.156.tgz"
    version = "0.0.156"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-mod"
    sha256 = "c148497a68ce521a02ed599d762caca24d28d66fb3f5402577bc423d879e0a83"
    source = "https://github.com/paketo-buildpacks/go-mod/archive/v0.0.125.tar.gz"
    source_sha256 = "ce249979f4c2722cdb84753d293b4be556868e12c6200239856e13bd5aef4a1a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-mod/releases/download/v0.0.125/go-mod-0.0.125.tgz"
    version = "0.0.125"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.156"

  [[order.group]]
    id = "paketo-buildpacks/go-mod"
    version = "0.0.125"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.156"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.137"
