api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dep"
    sha256 = "6920448f1aef9bbec9a459a3b0021d33301577b3dee7a1cba7175850223baba4"
    source = "https://github.com/paketo-buildpacks/dep/archive/v0.0.136.tar.gz"
    source_sha256 = "5d19df37e7349f144ce627ab154ca0b3cda45e7464f6ddbb19e1a6473f785dfa"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/dep/releases/download/v0.0.136/dep-0.0.136.tgz"
    version = "0.0.136"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-compiler"
    sha256 = "0d2c8ad02df610f3a1998956655f27bdd82074ade1427f598ac6fabc6a0e94bf"
    source = "https://github.com/paketo-buildpacks/go-compiler/archive/v0.0.154.tar.gz"
    source_sha256 = "af1df52c377e321a7354375e2af10bf08958e96917c0caa7a5e5146ea9f10799"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-compiler/releases/download/v0.0.154/go-compiler-0.0.154.tgz"
    version = "0.0.154"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-mod"
    sha256 = "c148497a68ce521a02ed599d762caca24d28d66fb3f5402577bc423d879e0a83"
    source = "https://github.com/paketo-buildpacks/go-mod/archive/v0.0.125.tar.gz"
    source_sha256 = "ce249979f4c2722cdb84753d293b4be556868e12c6200239856e13bd5aef4a1a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-mod/releases/download/v0.0.125/go-mod-0.0.125.tgz"
    version = "0.0.125"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.154"

  [[order.group]]
    id = "paketo-buildpacks/go-mod"
    version = "0.0.125"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.154"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.136"
