api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dep"
    sha256 = "a4b3d01e1ceb9891bde13002cb3ec83be9a4cc7f749e99063e49979503c2ee1b"
    source = "https://github.com/paketo-buildpacks/dep/archive/v0.0.145.tar.gz"
    source_sha256 = "3a3c3c83c81cfc8679ee40b7980b84d44136790ff8004f6624532ce0ce5fda14"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/dep/releases/download/v0.0.145/dep-0.0.145.tgz"
    version = "0.0.145"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-dist"
    sha256 = "3ab89d24521073d77fb07060bcfd5773c8db94b0c08e02e72d575cdcaed1573f"
    source = "https://github.com/paketo-buildpacks/go-dist/archive/v0.0.176.tar.gz"
    source_sha256 = "d0077e567360f6a332b18a084e4810c8883c5fd5f562424d2a9a428bd6dd011e"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/go-dist/releases/download/v0.0.176/go-dist-0.0.176.tgz"
    version = "0.0.176"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-mod"
    sha256 = "e6c87c2af6ac334f23439d90dc4d651a124fda45ae034240e53ae0ec68833c09"
    source = "https://github.com/paketo-buildpacks/go-mod/archive/v0.0.133.tar.gz"
    source_sha256 = "4b4c524867b287484f4255447004c9bd0971582997d5afcdaf23340b11a57d7a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-mod/releases/download/v0.0.133/go-mod-0.0.133.tgz"
    version = "0.0.133"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-build"
    sha256 = "2abe444fe5e2f9fe8a8763fa1613b10a0c5f35584c65676aa5a559bf57e97b9a"
    source = "https://github.com/paketo-buildpacks/go-build/archive/v0.0.2.tar.gz"
    source_sha256 = "732c101a5467a8c64ad48a80b2c9616dc99b6735d07757435895516a038f4026"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/go-build/releases/download/v0.0.2/go-build-0.0.2.tgz"
    version = "0.0.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.176"

  [[order.group]]
    id = "paketo-buildpacks/go-mod"
    version = "0.0.133"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.176"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.145"
