api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dep"
    sha256 = "b2922b07cdf415f69d8199b5d19f638b6a662e501ce16eec8a736f6efd58581f"
    source = "https://github.com/paketo-buildpacks/dep/archive/v0.0.146.tar.gz"
    source_sha256 = "7b544c90d6e7cdd26f57fad39becdb43416d9468622781be18d2242773ef8b42"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/dep/releases/download/v0.0.146/dep-0.0.146.tgz"
    version = "0.0.146"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-dist"
    sha256 = "6778ef60c49348920738a6cf183104cc84bfb5915f5829dd065388738ffcb83a"
    source = "https://github.com/paketo-buildpacks/go-dist/archive/v0.0.177.tar.gz"
    source_sha256 = "40afcb2ba07fae75b37c080956c2757986fd5951a7f27960bd11c13f1ae8bb4b"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/go-dist/releases/download/v0.0.177/go-dist-0.0.177.tgz"
    version = "0.0.177"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-mod"
    sha256 = "e6c87c2af6ac334f23439d90dc4d651a124fda45ae034240e53ae0ec68833c09"
    source = "https://github.com/paketo-buildpacks/go-mod/archive/v0.0.133.tar.gz"
    source_sha256 = "4b4c524867b287484f4255447004c9bd0971582997d5afcdaf23340b11a57d7a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-mod/releases/download/v0.0.133/go-mod-0.0.133.tgz"
    version = "0.0.133"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-build"
    sha256 = "c55e1ec10d8e49043cac4569c1091018d78ee5a1b524914f03e1d1b454944bfb"
    source = "https://github.com/paketo-buildpacks/go-build/archive/v0.0.5.tar.gz"
    source_sha256 = "428f87229a853266e46b0878ebb16fefe73bd00437663298eed4e625ffe9e551"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/go-build/releases/download/v0.0.5/go-build-0.0.5.tgz"
    version = "0.0.5"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.177"

  [[order.group]]
    id = "paketo-buildpacks/go-mod"
    version = "0.0.133"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.177"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.146"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.177"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.0.5"
