api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dep"
    sha256 = "955b8562403eb8e85f034d7e031453d1de952369710b441caec3d98c5d1a49e1"
    source = "https://github.com/paketo-buildpacks/dep/archive/v0.0.134.tar.gz"
    source_sha256 = "a2c0b7e3ec33bed2ca5d901e65e9f7a28236e5a3d432fd6f815d0018529ece79"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/dep/releases/download/v0.0.134/dep-0.0.134.tgz"
    version = "0.0.134"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-compiler"
    sha256 = "1ab4ead193e81592cb7f5f5d045fae9fc8a91c07125749576636145ad0d3e6c6"
    source = "https://github.com/paketo-buildpacks/go-compiler/archive/v0.0.150.tar.gz"
    source_sha256 = "bc2d4d09e784f89bdab4cfddee4cf3d05add8f02c032f8bbc7a306ff6baab0a1"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-compiler/releases/download/v0.0.150/go-compiler-0.0.150.tgz"
    version = "0.0.150"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-mod"
    sha256 = "bacbf00d22e20fc1802da1219fdc3b040c523b831123fb93108ecdf3282236ec"
    source = "https://github.com/paketo-buildpacks/go-mod/archive/v0.0.124.tar.gz"
    source_sha256 = "5813d4471052b628d499f2eca0847e95a5a031f08c288a544054e685ec105c7e"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-mod/releases/download/v0.0.124/go-mod-0.0.124.tgz"
    version = "0.0.124"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.150"

  [[order.group]]
    id = "paketo-buildpacks/go-mod"
    version = "0.0.124"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.150"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.134"
