api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Go Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.202"

  [[order.group]]
    id = "paketo-buildpacks/go-mod-vendor"
    version = "0.0.156"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.0.23"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.202"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.161"

  [[order.group]]
    id = "paketo-buildpacks/dep-ensure"
    version = "0.0.20"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.0.23"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.202"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.0.23"
