api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dep"
    sha256 = "87bcd37fb4f1d1f83c594e8fffd3fb62511e21f5a95ed73c54855ebed5639f2a"
    source = "https://github.com/paketo-buildpacks/dep/archive/v0.0.138.tar.gz"
    source_sha256 = "50959e95cfba3ebfd7d743bff6923c06d675b34a56e03dd38f67d4d6a244dbfe"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/dep/releases/download/v0.0.138/dep-0.0.138.tgz"
    version = "0.0.138"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-compiler"
    sha256 = "caa1e8ae0106e5f95bc1ef3579c53a5a4fb49826125d99993e4e8964538c094b"
    source = "https://github.com/paketo-buildpacks/go-compiler/archive/v0.0.159.tar.gz"
    source_sha256 = "53604147d994585cc0a871981ff5006e7dac02951ccfca68b7cd8387c2e7056a"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-compiler/releases/download/v0.0.159/go-compiler-0.0.159.tgz"
    version = "0.0.159"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-mod"
    sha256 = "e06e57d5001d5369d89035d83a549a87452f6b171196ede1830a068a260a0f9b"
    source = "https://github.com/paketo-buildpacks/go-mod/archive/v0.0.127.tar.gz"
    source_sha256 = "5c940eb3ad1529484084e3a292b028cbe2713adac0420fb0907c8e15e0d1f12d"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-mod/releases/download/v0.0.127/go-mod-0.0.127.tgz"
    version = "0.0.127"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.159"

  [[order.group]]
    id = "paketo-buildpacks/go-mod"
    version = "0.0.127"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.159"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.138"
