api = "0.6"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Paketo Go Buildpack"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/go/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.0.1"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.0.1"

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.8.0"

  [[order.group]]
    id = "paketo-buildpacks/go-mod-vendor"
    version = "0.3.1"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.5.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.0.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.0.1"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.0.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.0.1"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.0.1"

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.8.0"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.1.1"

  [[order.group]]
    id = "paketo-buildpacks/dep-ensure"
    version = "0.1.1"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.5.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.0.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.0.1"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.0.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.0.1"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.0.1"

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.8.0"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.5.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.0.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.0.1"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.0.1"
