api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Paketo Go Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.2.0"

  [[order.group]]
    id = "paketo-buildpacks/go-mod-vendor"
    version = "0.0.166"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.0.34"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.2.0"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.169"

  [[order.group]]
    id = "paketo-buildpacks/dep-ensure"
    version = "0.0.30"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.0.34"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.2.0"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.0.34"
