api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dep"
    sha256 = "0bd492b568aad581d340021607844e8bd32b886f61b385eec14d08e512dce6c9"
    source = "https://github.com/paketo-buildpacks/dep/archive/v0.0.133.tar.gz"
    source_sha256 = "71a93c290170f6b7e3c1a676442e67d190625c543e6b94b8eff96989fc332810"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/dep/releases/download/v0.0.133/dep-0.0.133.tgz"
    version = "0.0.133"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-compiler"
    sha256 = "ce3c62ffb0819ea58f20e0b700f3b5e4685589a2bb279e807780ad7d82c3462a"
    source = "https://github.com/paketo-buildpacks/go-compiler/archive/v0.0.148.tar.gz"
    source_sha256 = "57000d52287a3e3e075ed739acd4a9ae17fbf232b6ac0dff67b4d223b7e93cbf"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-compiler/releases/download/v0.0.148/go-compiler-0.0.148.tgz"
    version = "0.0.148"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-mod"
    sha256 = "09a844f98d1d724437cc390db9f225339148780148a19b8775c4511b19fc3c34"
    source = "https://github.com/paketo-buildpacks/go-mod/archive/v0.0.123.tar.gz"
    source_sha256 = "9da7d6f98057f97939cc209cb46d4b0f98189d0c214a80e1d70132f201d50c67"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-mod/releases/download/v0.0.123/go-mod-0.0.123.tgz"
    version = "0.0.123"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.148"

  [[order.group]]
    id = "paketo-buildpacks/go-mod"
    version = "0.0.123"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.148"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.133"
