api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.190"

  [[order.group]]
    id = "paketo-buildpacks/go-mod-vendor"
    version = "0.0.143"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.190"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.150"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.190"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.0.12"
