api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dep"
    sha256 = "bfa56e61046e878ecd454017ae24f20c53c8eb18c1cae78a8c62fee7c80c8bb1"
    source = "https://github.com/paketo-buildpacks/dep/archive/v0.0.147.tar.gz"
    source_sha256 = "65dce06f883acad8121a959cb8eef7ac7f0aac547875fc37aa074c3991ee0f50"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/dep/releases/download/v0.0.147/dep-0.0.147.tgz"
    version = "0.0.147"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-dist"
    sha256 = "e0b5da0f7115feb9d254f662a33c73220cb43f4cba6e3337a296a0cc47b0c7db"
    source = "https://github.com/paketo-buildpacks/go-dist/archive/v0.0.180.tar.gz"
    source_sha256 = "7a920fc215e8afe418652f123fb61bb93b464aed7d2204da865af5eeff2ebe8e"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/go-dist/releases/download/v0.0.180/go-dist-0.0.180.tgz"
    version = "0.0.180"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-mod"
    sha256 = "c9f814811a855121d3320067c1abe328739896be51f316ae9ee5945fcf162a72"
    source = "https://github.com/paketo-buildpacks/go-mod/archive/v0.0.136.tar.gz"
    source_sha256 = "0eacd36eea4eb2019b63e85acca71b44d612092f1e48431c41aaaee4b417eff3"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-mod/releases/download/v0.0.136/go-mod-0.0.136.tgz"
    version = "0.0.136"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-build"
    sha256 = "c55e1ec10d8e49043cac4569c1091018d78ee5a1b524914f03e1d1b454944bfb"
    source = "https://github.com/paketo-buildpacks/go-build/archive/v0.0.5.tar.gz"
    source_sha256 = "428f87229a853266e46b0878ebb16fefe73bd00437663298eed4e625ffe9e551"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/go-build/releases/download/v0.0.5/go-build-0.0.5.tgz"
    version = "0.0.5"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.180"

  [[order.group]]
    id = "paketo-buildpacks/go-mod"
    version = "0.0.136"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.180"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.147"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.0.180"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.0.5"
