pull_request_rules:
  - name: Auto merge pull requests from dependabot
    conditions:
      - author=dependabot[bot]
      - status-success=Integration Tests
    actions:
      merge:
        strict: smart
        method: rebase
        bot_account: paketo-bot
      delete_head_branch: {}
