name: Test Pull Request

on:
  pull_request:
    branches:
    - main

concurrency:
  # only one instance of test suite per PR at one time
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  builders:
    name: Get Builders for Testing
    runs-on: ubuntu-latest
    outputs:
      builders: ${{ steps.builders.outputs.builders }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get builders from integration.json
      id: builders
      run: |
        source "${{ github.workspace }}/scripts/.util/builders.sh"

        builders="$(util::builders::list "${{ github.workspace }}/integration.json")"
        printf "Output: %s\n" "${builders}"
        printf "::set-output name=builders::%s\n" "${builders}"

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [builders]
    strategy:
      matrix:
        builder: ${{ fromJSON(needs.builders.outputs.builders) }}
      fail-fast: false  # don't cancel all test jobs when one fails
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x

    - name: Checkout
      uses: actions/checkout@v3

    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true

    - name: Run Integration Tests
      run: ./scripts/integration.sh --builder ${{ matrix.builder }}

  upload:
    name: Upload Workflow Event Payload
    runs-on: ubuntu-latest
    steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: event-payload
        path: ${{ github.event_path }}
