name: Update shared github-config

on:
  schedule:
  - cron: '15 */1 * * *'
  workflow_dispatch: {}

jobs:
  build:
    name: Create PR to update shared files
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

    - name: Checkout github-config
      uses: actions/checkout@v2
      with:
        repository: paketo-buildpacks/github-config
        path: github-config

    - name: Checkout Branch
      uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
      with:
        branch: automation/github-config/update

    - name: Run the sync action
      uses: paketo-buildpacks/github-config/actions/sync@main
      with:
        workspace: /github/workspace
        config: /github/workspace/github-config/language-family

    - name: Cleanup
      run: rm -rf github-config

    - name: Commit
      id: commit
      uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
      with:
        message: "Updating github-config"
        pathspec: "."
        keyid: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY_ID }}
        key: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY }}

    - name: Push Branch
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
      with:
        branch: automation/github-config/update

    - name: Open Pull Request
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/open@main
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        title: "Updates github-config"
        branch: automation/github-config/update
